<?php

use Illuminate\Database\Seeder;

class Municipioss {
    public $municipio;
    public $id_depto;

    public function guardar($id_depto,$municipio){
        $municipios = factory(App\Municipality::class)->create([
            'departament_id' => $id_depto,
            'name' => $municipio
        ]);
    }
}

class MunicipalitySeeder extends Seeder
{
    public function run()
    {
      $municipioss = new Municipioss();
      $municipioss->guardar("1","CHANAL");
      $municipioss->guardar("1","CHISEC");
      $municipioss->guardar("1","COBÁN");
      $municipioss->guardar("1","FRAY BARTOLOMÉ DE LAS CASAS");
      $municipioss->guardar("1","LANQUÍN");
      $municipioss->guardar("1","PANZÓS");
      $municipioss->guardar("1","SAN CRISTÓBAL VERAPAZ");
      $municipioss->guardar("1","SAN JUAN CHAMELCO");
      $municipioss->guardar("1","SAN PEDRO CARCHÁ");
      $municipioss->guardar("1","SANTA CATALINA LA TINTA");
      $municipioss->guardar("1","SANTA CRUZ VERAPAZ");
      $municipioss->guardar("1","SANTA MARÍA CAHABÓN");
      $municipioss->guardar("1","SENAHÚ");
      $municipioss->guardar("1","TACTIC");
      $municipioss->guardar("1","TAMAHÚ");
      $municipioss->guardar("1","TUCURÚ");
      $municipioss->guardar("1","RAXUHA");
      $municipioss->guardar("2","CUBULCO");
      $municipioss->guardar("2","GRANADOS");
      $municipioss->guardar("2","PARULHÁ");
      $municipioss->guardar("2","RABINAL");
      $municipioss->guardar("2","SALAMÁ");
      $municipioss->guardar("2","SAN JERÓNIMO");
      $municipioss->guardar("2","SAN MIGUEL CHICAJ");
      $municipioss->guardar("2","SANTA CRUZ EL CHOL");
      $municipioss->guardar("3","ACATENANGO");
      $municipioss->guardar("3","CHIMALTENANGO");
      $municipioss->guardar("3","EL TEJAR");
      $municipioss->guardar("3","PARRAMOS");
      $municipioss->guardar("3","PATZICÍA");
      $municipioss->guardar("3","PATZÚN");
      $municipioss->guardar("3","SAN ADRÉS ITZAPA");
      $municipioss->guardar("3","SAN JOSÉ POAQUIL");
      $municipioss->guardar("3","SAN JUAN COMALAPA");
      $municipioss->guardar("3","SAN MARTÍN JILOTEPEQUE");
      $municipioss->guardar("3","SAN MIGUEL POCHUTA");
      $municipioss->guardar("3","SAN PEDRO YEPOCAPA");
      $municipioss->guardar("3","SANTA APOLONIA");
      $municipioss->guardar("3","SANTA CRUZ BALANYÁ");
      $municipioss->guardar("3","TECPÁN GUATEMALA");
      $municipioss->guardar("3","ZARAGOZA");
      $municipioss->guardar("4","CAMOTÁN");
      $municipioss->guardar("4","CHIQUIMULA");
      $municipioss->guardar("4","CONCEPCIÓN LAS MINAS");
      $municipioss->guardar("4","ESQUIPULAS");
      $municipioss->guardar("4","IPALA");
      $municipioss->guardar("4","JOCOTÁN");
      $municipioss->guardar("4","OLAPA");
      $municipioss->guardar("4","QUEZALTEPEQUE");
      $municipioss->guardar("4","SAN JACINTO");
      $municipioss->guardar("4","SAN JOSÉ LA ARADA");
      $municipioss->guardar("4","SAN JUAN ERMITA");
      $municipioss->guardar("5","AMATITLÁN");
      $municipioss->guardar("5","CHINAUTLA");
      $municipioss->guardar("5","CHUARRANCHO");
      $municipioss->guardar("5","FRAIJANES");
      $municipioss->guardar("5","GUATEMALA");
      $municipioss->guardar("5","MIXCO");
      $municipioss->guardar("5","PALENCIA");
      $municipioss->guardar("5","SAN JOSÉ DEL GOLFO");
      $municipioss->guardar("5","SAN JOSÉ PINULA");
      $municipioss->guardar("5","SAN JUAN SACATEPEQUEZ");
      $municipioss->guardar("5","SAN MIGUEL PETAPA");
      $municipioss->guardar("5","SAN PEDRO AYAMPUC");
      $municipioss->guardar("5","SAN PEDRO SACATEPEQUEZ");
      $municipioss->guardar("5","SAN RAYMUNDO");
      $municipioss->guardar("5","SANTA CATARINA PINULA");
      $municipioss->guardar("5","VILLA CANALES");
      $municipioss->guardar("5","VILLA NUEVA");
      $municipioss->guardar("6","EL JÍCARO");
      $municipioss->guardar("6","GUASTATOYA");
      $municipioss->guardar("6","MORAZÁN");
      $municipioss->guardar("6","SAN AGUSTÍN ACASAGUASTLÁN");
      $municipioss->guardar("6","SAN ANTONIO LA PAZ");
      $municipioss->guardar("6","SAN CRISTÓBAL ACASAGUASTLÁN");
      $municipioss->guardar("6","SANARATE");
      $municipioss->guardar("6","SANSARE");
      $municipioss->guardar("7","ESCUINTLA");
      $municipioss->guardar("7","GUANAGAZAPA");
      $municipioss->guardar("7","IZTAPA");
      $municipioss->guardar("7","LA DEMOCRACIA");
      $municipioss->guardar("7","LA GOMERA");
      $municipioss->guardar("7","MASAGUA");
      $municipioss->guardar("7","NUEVA CONCEPCIÓN");
      $municipioss->guardar("7","PALÍN");
      $municipioss->guardar("7","SAN JOSÉ");
      $municipioss->guardar("7","SAN VICENTE PACAYA");
      $municipioss->guardar("7","SANTA LUCÍA COTZUMALGUAPA");
      $municipioss->guardar("7","SIPACATE");
      $municipioss->guardar("7","SIQUINALÁ");
      $municipioss->guardar("7","TIQUISATE");
      $municipioss->guardar("8","AGUACATÁN");
      $municipioss->guardar("8","CHIANTLA");
      $municipioss->guardar("8","COLOTENANGO");
      $municipioss->guardar("8","CONCEPCIÓN HUISTA");
      $municipioss->guardar("8","CUILCO");
      $municipioss->guardar("8","HUEHUETENANGO");
      $municipioss->guardar("8","JACALTENANGO");
      $municipioss->guardar("8","LA DEMOCRACIA");
      $municipioss->guardar("8","LA LIBERTAD");
      $municipioss->guardar("8","MALACATANCITO");
      $municipioss->guardar("8","NENTÓN");
      $municipioss->guardar("8","SAN ANTONIO HUISTA");
      $municipioss->guardar("8","SAN GASPAR IXCHIL");
      $municipioss->guardar("8","SAN ILDEFONSO IXTAHUACÁN");
      $municipioss->guardar("8","SAN JUAN ATITÁN");
      $municipioss->guardar("8","SAN JUAN IXCOY");
      $municipioss->guardar("8","SAN MATEO IXTATÁN");
      $municipioss->guardar("8","SAN MIGUEL ACATÁN");
      $municipioss->guardar("8","SAN PEDRO NECTA");
      $municipioss->guardar("8","SAN PEDRO SOLOMA");
      $municipioss->guardar("8","SAN RAFAEL LA INDEPENDENCIA");
      $municipioss->guardar("8","SAN RAFAEL PETZAL");
      $municipioss->guardar("8","SAN SEBASTIÁN COATÁN");
      $municipioss->guardar("8","SAN SEBASTIÁN HUEHUETENANGO");
      $municipioss->guardar("8","SANTA ANA HUISTA");
      $municipioss->guardar("8","SANTA BÁRBARA");
      $municipioss->guardar("8","SANTA CRUZ BARILLAS");
      $municipioss->guardar("8","SANTA EULALIA");
      $municipioss->guardar("8","SANTIAGO CHIMALTENANGO");
      $municipioss->guardar("8","TECTITÁN");
      $municipioss->guardar("8","TODOS SANTOS CUCHUMATÁN");
      $municipioss->guardar("8","UNIÓN CANTINIL");
      $municipioss->guardar("9","EL ESTOR");
      $municipioss->guardar("9","LIVINGSTON");
      $municipioss->guardar("9","LOS AMATES");
      $municipioss->guardar("9","MORALES");
      $municipioss->guardar("9","PUERTO BARRIOS");
      $municipioss->guardar("10","JALAPA");
      $municipioss->guardar("10","MATAQUESCUINTLA");
      $municipioss->guardar("10","MONJAS");
      $municipioss->guardar("10","SAN CARLOS ALZATATE");
      $municipioss->guardar("10","SAN LUIS JILOTEPEQUE");
      $municipioss->guardar("10","SAN MANUEL CHAPARRÓN");
      $municipioss->guardar("10","SAN PEDRO PINULA");
      $municipioss->guardar("11","AGUA BLANCA");
      $municipioss->guardar("11","ASUNCIÓN MITA");
      $municipioss->guardar("11","ATESCATEMPA");
      $municipioss->guardar("11","COMAPA");
      $municipioss->guardar("11","CONGUACO");
      $municipioss->guardar("11","EL ADELANTO");
      $municipioss->guardar("11","EL PROGRESO");
      $municipioss->guardar("11","JALPATAGUA");
      $municipioss->guardar("11","JEREZ");
      $municipioss->guardar("11","JUTIAPA");
      $municipioss->guardar("11","MOYUTA");
      $municipioss->guardar("11","PASACO");
      $municipioss->guardar("11","QUEZAPA");
      $municipioss->guardar("11","SAN JOSÉ ACATEMPA");
      $municipioss->guardar("11","SANTA CATARINA MINTA");
      $municipioss->guardar("11","YUPILTEPEQUE");
      $municipioss->guardar("11","ZAPOTITLÁN");
      $municipioss->guardar("12","FLORES");
      $municipioss->guardar("12","DOLORES");
      $municipioss->guardar("12","EL CHAL");
      $municipioss->guardar("12","LA LIBERTAD");
      $municipioss->guardar("12","LAS CRUCES");
      $municipioss->guardar("12","MELCHOR DE MENCOS");
      $municipioss->guardar("12","POPTÚN");
      $municipioss->guardar("12","SAN ANDRÉS");
      $municipioss->guardar("12","SAN BENITO");
      $municipioss->guardar("12","SAN FRANCHISCO");
      $municipioss->guardar("12","SAN JOSÉ");
      $municipioss->guardar("12","SAN LUIS");
      $municipioss->guardar("12","SANTA ANA ");
      $municipioss->guardar("12","SAYAXCHÉ");
      $municipioss->guardar("13","ALMOLONGA");
      $municipioss->guardar("13","CABRICÁN");
      $municipioss->guardar("13","CAJOLÁ");
      $municipioss->guardar("13","CANTEL");
      $municipioss->guardar("13","COATEPEQUE");
      $municipioss->guardar("13","COLOMBA");
      $municipioss->guardar("13","CONCEPCIÓN CHIQUIRICHAPA");
      $municipioss->guardar("13","EL PALMAR");
      $municipioss->guardar("13","FLORES COSTA CUCA");
      $municipioss->guardar("13","GÉNOVA");
      $municipioss->guardar("13","HUITÁN");
      $municipioss->guardar("13","LA ESPERANZA");
      $municipioss->guardar("13","OLINTEPEQUE");
      $municipioss->guardar("13","OSTUNCALCO");
      $municipioss->guardar("13","PALESTINA DE LOS ALTOS");
      $municipioss->guardar("13","QUETZALTENANGO");
      $municipioss->guardar("13","SALCAJÁ");
      $municipioss->guardar("13","SAN CARLOS SIJA");
      $municipioss->guardar("13","SAN FRANCISCO LA UNIÓN");
      $municipioss->guardar("13","SAN MARTÍN SACATEPÉQUEZ");
      $municipioss->guardar("13","SAN MATEO");
      $municipioss->guardar("13","SAN MIGUEL SIGÜILA");
      $municipioss->guardar("13","SIBILIA");
      $municipioss->guardar("13","ZUNIL");
      $municipioss->guardar("14","SANTA CRUZ DEL QUICHÉ");
      $municipioss->guardar("14","CANILLÁ");
      $municipioss->guardar("14","CHAJUL");
      $municipioss->guardar("14","CHICAMÁN");
      $municipioss->guardar("14","CHICHÉ");
      $municipioss->guardar("14","CHICHICASTENANGO");
      $municipioss->guardar("14","CHINIQUE");
      $municipioss->guardar("14","CUNÉN");
      $municipioss->guardar("14","IXCÁN");
      $municipioss->guardar("14","JOYABAJ");
      $municipioss->guardar("14","PACHULUM");
      $municipioss->guardar("14","PATZITÉ");
      $municipioss->guardar("14","SACAPULAS");
      $municipioss->guardar("14","SAN ANDRÉS SAJCABAJÁ");
      $municipioss->guardar("14","SAN ANTONIO ILOTENANGO");
      $municipioss->guardar("14","SAN BARTOLOMÉ JOCOTENANGO");
      $municipioss->guardar("14","SAN JUAN COTZAL");
      $municipioss->guardar("14","SAN PEDRO JOCOPILAS");
      $municipioss->guardar("14","SANTA MARÍA NEBAJ");
      $municipioss->guardar("14","USPATÁN");
      $municipioss->guardar("14","ZACUALPA");
      $municipioss->guardar("15","CHAMPERICO");
      $municipioss->guardar("15","EL ASINTAL");
      $municipioss->guardar("15","NUEVO SAN CARLOS");
      $municipioss->guardar("15","RETALHULEU");
      $municipioss->guardar("15","SAN ADRÉS VILLA SECA");
      $municipioss->guardar("15","SAN FELIPE");
      $municipioss->guardar("15","SAN MARTÍN ZAPOTITLÁN");
      $municipioss->guardar("15","SAN SEBASTIÁN");
      $municipioss->guardar("15","SANTA CRUZ MULUÁ");
      $municipioss->guardar("16","ALOTENANGO");
      $municipioss->guardar("16","ANTIGUA GUATEMALA");
      $municipioss->guardar("16","CIUDAD VIEJA");
      $municipioss->guardar("16","JOCOTENANGO");
      $municipioss->guardar("16","MAGDALENA MILPAS ALTAS");
      $municipioss->guardar("16","PASTORES");
      $municipioss->guardar("16","SAN ANTONIO AGUAS CALIENTES");
      $municipioss->guardar("16","SAN BARTOLOMÉ MILPAS ALTAS");
      $municipioss->guardar("16","SAN LUCAS SACATEPÉQUEZ");
      $municipioss->guardar("16","SAN MIGUEL DUEÑAS");
      $municipioss->guardar("16","SANTA CATARINA BARAHONA");
      $municipioss->guardar("16","SANTA LUCÍA MILPAS ALTAS");
      $municipioss->guardar("16","SANTA MARÍA DE JESÚS");
      $municipioss->guardar("16","SANTIAGO SACATEPÉQUEZ");
      $municipioss->guardar("16","SANTO DOMINGO XENACOJ");
      $municipioss->guardar("16","SUMPANGO");
      $municipioss->guardar("17","AYUTLA");
      $municipioss->guardar("17","CATARINA");
      $municipioss->guardar("17","COMITANCILLO");
      $municipioss->guardar("17","CONCEPCIÓN TATUAPA");
      $municipioss->guardar("17","EL QUETZAL");
      $municipioss->guardar("17","EL TUMBADOR");
      $municipioss->guardar("17","ESQUIPULAS PALO GORDO");
      $municipioss->guardar("17","IXCHIGUÁN");
      $municipioss->guardar("17","LA BLANCA");
      $municipioss->guardar("17","LA REFORMA");
      $municipioss->guardar("17","MALACATÁN");
      $municipioss->guardar("17","NUEVO PROGRESO");
      $municipioss->guardar("17","OCÓS");
      $municipioss->guardar("17","PAJAPITA");
      $municipioss->guardar("17","RÍO BLANCO");
      $municipioss->guardar("17","SAN ANTONIO SACATEPÉQUEZ");
      $municipioss->guardar("17","SAN CRISTÓBALO CUCHO");
      $municipioss->guardar("17","SAN JOSÉ EL RODEO");
      $municipioss->guardar("17","SAN JOSÉ OJETENAM");
      $municipioss->guardar("17","SAN LORENZO");
      $municipioss->guardar("17","SAN MARCOS");
      $municipioss->guardar("17","SAN MIGUEL IXTAHUACÁN");
      $municipioss->guardar("17","SAN PABLO");
      $municipioss->guardar("17","SAN PEDRO SACATEPÉQUEZ");
      $municipioss->guardar("17","SAN RAFAEL PIE DE LA CUESTA");
      $municipioss->guardar("17","SBINAL");
      $municipioss->guardar("17","SIPACAPA");
      $municipioss->guardar("17","TACANÁ");
      $municipioss->guardar("17","TAJUMULCO");
      $municipioss->guardar("17","TEJUTLA");
      $municipioss->guardar("18","BARBERENA");
      $municipioss->guardar("18","CASILLAS");
      $municipioss->guardar("18","CHIQUIMULILLA");
      $municipioss->guardar("18","CUILAPA");
      $municipioss->guardar("18","GUAZACAPÁN");
      $municipioss->guardar("18","NUEVA SANTA ROSA");
      $municipioss->guardar("18","ORATORIO");
      $municipioss->guardar("18","PUEBLO NUEVO VIÑAS");
      $municipioss->guardar("18","SAN JUAN TECUACO");
      $municipioss->guardar("18","SAN RAFAEL LAS FLORES");
      $municipioss->guardar("18","SANTA CRUZ NARANJO");
      $municipioss->guardar("18","SANTA MARÍA IXHUATÁN");
      $municipioss->guardar("18","SANTA ROSA DE LIMA");
      $municipioss->guardar("18","TAXISCO");
      $municipioss->guardar("19","CONCEPCIÓN");
      $municipioss->guardar("19","NAHUALÁ");
      $municipioss->guardar("19","PANAJACHEL");
      $municipioss->guardar("19","SAN ANDRÉS SEMETABAJ");
      $municipioss->guardar("19","SAN ANTONIO PALOPÓ");
      $municipioss->guardar("19","SAN JOSÉ CHACAYÁ");
      $municipioss->guardar("19","SAN JUAN LA LAGUNA");
      $municipioss->guardar("19","SAN LUCAS TOLIMÁN");
      $municipioss->guardar("19","SAN MARCOS LA LAGUNA");
      $municipioss->guardar("19","SAN PABLO LA LAGUNA");
      $municipioss->guardar("19","SAN PEDRO LA LAGUNA");
      $municipioss->guardar("19","SANTA CATARINA IXTAHUACÁN");
      $municipioss->guardar("19","SANTA CATARINA PALOPÓ");
      $municipioss->guardar("19","SANTA CLARA LA LAGUNA");
      $municipioss->guardar("19","SANTA CRUZ LA LAGUNA");
      $municipioss->guardar("19","SANTA LUCÍA UTATLÁN");
      $municipioss->guardar("19","SANTA MARÍA VISITACIÓN");
      $municipioss->guardar("19","SANTIAGO ATITLÁN");
      $municipioss->guardar("19","SOLOLÁ");
      $municipioss->guardar("20","CHICACAO");
      $municipioss->guardar("20","CUYOTENANGO");
      $municipioss->guardar("20","MAZATENANGO");
      $municipioss->guardar("20","PATULUL");
      $municipioss->guardar("20","PUEBLO NUEVO");
      $municipioss->guardar("20","RÍO BRAVO");
      $municipioss->guardar("20","SAMAYAC");
      $municipioss->guardar("20","SAN ANTONIO SUCHITEPÉQUEZ");
      $municipioss->guardar("20","SAN BEMARDINO");
      $municipioss->guardar("20","SAN FRANCISCO ZAPOTITLÁN");
      $municipioss->guardar("20","SAN GABRIEL");
      $municipioss->guardar("20","SAN JOSÉ EL ÍDOLO");
      $municipioss->guardar("20","SAN JOSÉ LA MAQUINA");
      $municipioss->guardar("20","SAN JUAN BAUTISTA");
      $municipioss->guardar("20","SAN LORENZO");
      $municipioss->guardar("20","SAN MIGUEL PANÁN");
      $municipioss->guardar("20","SAN PABLO JOCOPILAS");
      $municipioss->guardar("20","SANTA BÁRBARA");
      $municipioss->guardar("20","SANTO DOMINGO SUCHITEPÉQUEZ");
      $municipioss->guardar("20","SANTO TOMÁS LA UNIÓN");
      $municipioss->guardar("20","ZUNILITO");
      $municipioss->guardar("21","MOMOSTENANGO");
      $municipioss->guardar("21","SAN ANDRÉS XECUL");
      $municipioss->guardar("21","SAN BARTOLO AGUAS CALIENTES");
      $municipioss->guardar("21","SAN CRISTÓBAL TOTONICAPÁN");
      $municipioss->guardar("21","SAN FRANCISCO EL ALTO");
      $municipioss->guardar("21","SANTA LUCÍA LA REFORMA");
      $municipioss->guardar("21","SANTA MARÍA CHIQUIMULA");
      $municipioss->guardar("21","TOTONICAPÁN");
      $municipioss->guardar("22","CABAÑAS");
      $municipioss->guardar("22","ESTANZUELA");
      $municipioss->guardar("22","GUALÁN");
      $municipioss->guardar("22","HUITÉ");
      $municipioss->guardar("22","LA UNIÓN");
      $municipioss->guardar("22","RÍO HONDO");
      $municipioss->guardar("22","SAN DIEGO");
      $municipioss->guardar("22","SAN JORGE");
      $municipioss->guardar("22","TECULUTÁN");
      $municipioss->guardar("22","USUMATLÁN");
      $municipioss->guardar("22","ZACAPA");
  }
}
